### ISSUE TITLE
python tracking/create_default_local_file.py --workspace_dir . --data_dir ./data --save_dir ./output

### ISSUE THREAD

**Issue by EricLiuUCAS** [Event-AHU/Mamba_FETrack#8]
ModuleNotFoundError: No module named 'lib.train.data'

I can‘t find this "lib.train.data".

**Comment by stepstardream** [comment]
me too

**Comment by stepstardream** [comment]
I create the data_dir ./data --save_dir ./output and  pretrained_models  than run python tracking/test.py mamba_fetrack 
mamba_fetrack_fe108 --dataset fe108 --threads 1 --num_gpus 1
WARNING: You are using tensorboardX instead sis you have a too old pytorch version.
Traceback (most recent call last):
  File "/home/lydvp/Mamba/Mamba_FETrack/Mamba_FETrack/tracking/test.py", line 9, in <module>
    from lib.test.evaluation import get_dataset
  File "/home/lydvp/Mamba/Mamba_FETrack/Mamba_FETrack/tracking/../lib/test/evaluation/__init__.py", line 1, in <module>
    from .data import Sequence
  File "/home/lydvp/Mamba/Mamba_FETrack/Mamba_FETrack/tracking/../lib/test/evaluation/data.py", line 3, in <module>
    from lib.train.data.image_loader import imread_indexed
ModuleNotFoundError: No module named 'lib.train.data'

**Comment by stepstardream** [comment]
I create the data_dir ./data --save_dir ./output and pretrained_models than run python tracking/test.py mamba_fetrack    
ModuleNotFoundError: No module named 'lib.train.data'

**Comment by wsasdsda** [comment]
Hello, thank you for your attention. Our code encountered some issues during upload, we have updated it first!

**Comment by EricLiuUCAS** [comment]
the issue is solved，thank you so much.





------------------ Original ------------------
From: Shiao Wang ***@***.***&gt;
Date: Sun,Dec 29,2024 11:10 AM
To: Event-AHU/Mamba_FETrack ***@***.***&gt;
Cc: EricLiuUCAS ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [Event-AHU/Mamba_FETrack] pythontracking/create_default_local_file.py --workspace_dir . --data_dir ./data--save_dir ./output (Issue #8)





 
Hello, thank you for your attention. Our code encountered some issues during upload, we have updated it first!
